// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR5OEXf8pKUm0UxlNu6tjkQmD6FtkyY6k',
    appId: '1:853332714317:web:10dce48ce9464fc91b8d04',
    messagingSenderId: '853332714317',
    projectId: 'safety-manager-b52dd',
    authDomain: 'safety-manager-b52dd.firebaseapp.com',
    databaseURL: 'https://safety-manager-b52dd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'safety-manager-b52dd.firebasestorage.app',
    measurementId: 'G-JBPGYNES57',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsijGn3WNARcOyh4GFi45nOLOx1eWaJlA',
    appId: '1:853332714317:android:9355c737aff77f0f1b8d04',
    messagingSenderId: '853332714317',
    projectId: 'safety-manager-b52dd',
    databaseURL: 'https://safety-manager-b52dd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'safety-manager-b52dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfIoK44LNDrnwnWG9wMEq1LgKPCiwkJLU',
    appId: '1:853332714317:ios:bb4192fec54e29b11b8d04',
    messagingSenderId: '853332714317',
    projectId: 'safety-manager-b52dd',
    databaseURL: 'https://safety-manager-b52dd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'safety-manager-b52dd.firebasestorage.app',
    iosBundleId: 'com.example.safetyManagerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfIoK44LNDrnwnWG9wMEq1LgKPCiwkJLU',
    appId: '1:853332714317:ios:bb4192fec54e29b11b8d04',
    messagingSenderId: '853332714317',
    projectId: 'safety-manager-b52dd',
    databaseURL: 'https://safety-manager-b52dd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'safety-manager-b52dd.firebasestorage.app',
    iosBundleId: 'com.example.safetyManagerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCR5OEXf8pKUm0UxlNu6tjkQmD6FtkyY6k',
    appId: '1:853332714317:web:7b06c3052bb4f0421b8d04',
    messagingSenderId: '853332714317',
    projectId: 'safety-manager-b52dd',
    authDomain: 'safety-manager-b52dd.firebaseapp.com',
    databaseURL: 'https://safety-manager-b52dd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'safety-manager-b52dd.firebasestorage.app',
    measurementId: 'G-DJRX405VJS',
  );
}
